kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: swe599-demo
  name: html-syntax-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-syntax-checker-app
  template:
    metadata:
      labels:
        app: html-syntax-checker-app
    spec:
      containers:
        - name: html-syntax-checker
          image: html-syntax-checker
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  namespace: swe599-demo
  name: html-syntax-checker-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
  selector:
    app: html-operations-app

